
Tracker:AddLocations("locations/CityEscape.json")
Tracker:AddLocations("locations/WildCanyon.json")
Tracker:AddLocations("locations/PrisonLane.json")
Tracker:AddLocations("locations/MetalHarbor.json")
Tracker:AddLocations("locations/GreenForest.json")
Tracker:AddLocations("locations/PumpkinHill.json")
Tracker:AddLocations("locations/MissionStreet.json")
Tracker:AddLocations("locations/AquaticMine.json")
Tracker:AddLocations("locations/Route101.json")
Tracker:AddLocations("locations/HiddenBase.json")
Tracker:AddLocations("locations/PyramidCave.json")
Tracker:AddLocations("locations/DeathChamber.json")
Tracker:AddLocations("locations/EternalEngine.json")
Tracker:AddLocations("locations/MeteorHerd.json")
Tracker:AddLocations("locations/CrazyGadget.json")
Tracker:AddLocations("locations/FinalRush.json")

Tracker:AddLocations("locations/IronGate.json")
Tracker:AddLocations("locations/DryLagoon.json")
Tracker:AddLocations("locations/SandOcean.json")
Tracker:AddLocations("locations/RadicalHighway.json")
Tracker:AddLocations("locations/LostColony.json")
Tracker:AddLocations("locations/EggQuarters.json")
Tracker:AddLocations("locations/WeaponsBed.json")
Tracker:AddLocations("locations/SecurityHall.json")
Tracker:AddLocations("locations/WhiteJungle.json")
Tracker:AddLocations("locations/Route280.json")
Tracker:AddLocations("locations/SkyRail.json")
Tracker:AddLocations("locations/MadSpace.json")
Tracker:AddLocations("locations/CosmicWall.json")
Tracker:AddLocations("locations/FinalChase.json")

Tracker:AddLocations("locations/GreenHill.json")

Tracker:AddLocations("locations/GateBosses.json")
Tracker:AddLocations("locations/BossRushBosses.json")

Tracker:AddLocations("locations/KartRace.json")

Tracker:AddLocations("locations/ChaoGardenBeginner.json")
Tracker:AddLocations("locations/ChaoGardenIntermediate.json")
Tracker:AddLocations("locations/ChaoGardenExpert.json")
Tracker:AddLocations("locations/ChaoGardenKarate.json")

Tracker:AddLocations("locations/CannonsCore.json")